### ISSUE TITLE
Bug after installing

### ISSUE THREAD

**Issue by EdenDolev** [smartin015/continuousprint#248] opened 2024-04-25 13:25 UTC
**Describe the bug**
So after a fresh install ai get a bug without any description, as seen in picture

**To Reproduce**
1. install the plugin
2. enter the plugin page

**Expected behavior**
i wanted to see the plugin works without errors

**Screenshots**
![Screenshot 2024-04-25 at 16 20 47](https://github.com/smartin015/continuousprint/assets/104971478/66a2dff7-f113-437e-808d-98975b0e8ef8)

**System info:**
system info:
[octoprint-systeminfo-20240425141931.zip](https://github.com/smartin015/continuousprint/files/15110540/octoprint-systeminfo-20240425141931.zip)

**Browser logs:**

[browserlogs.zip](https://github.com/smartin015/continuousprint/files/15110602/browserlogs.zip)

**Comment by smartin015** [comment] 2024-04-27 15:46
Hey, thanks for the report - this looks like a duplicate of #249. You can follow along with the fix there.

**Closed by smartin015** 2024-04-27 15:46 UTC
Labels: bug
