### ISSUE TITLE
conflic with Octodash ?

### ISSUE THREAD

**Issue by neocats2001** [smartin015/continuousprint#250] opened 2024-04-26 07:09 UTC
![Capture](https://github.com/smartin015/continuousprint/assets/82447377/14ddb0c7-dbfe-4e20-8479-1d0c21e34697)

what happend ?

Thanks

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System info:**
Follow the instructions [here](https://community.octoprint.org/t/what-is-a-systeminfo-bundle-and-how-can-i-obtain-one/29887) to generate an OctoPrint system bundle, and attach it to this issue.

**Browser logs:**
Collect the console logs for your browser and upload them to this issue. See [here](https://support.shortpoint.com/support/solutions/articles/1000222881-save-browser-console-file) for instructions on how to do this for different browsers.

**Additional context**

**Comment by smartin015** [comment] 2024-04-27 15:46
Hey, thanks for the report - this looks like a duplicate of #249. You can follow along with the fix there.

**Closed by smartin015** 2024-04-27 15:46 UTC
Labels: bug
