### ISSUE TITLE
Continuous Print Error after Octoprint Update - Hauke

### ISSUE THREAD

**Issue by YoungVolks** [smartin015/continuousprint#251] opened 2024-04-26 13:19 UTC
**Describe the bug**
Downloaded latest version (V1.10.0) of Ocotprint as of 4/26/2024.  Had previously used Continuous Print successfully for over 50 days. 
Continuous print now does not work and shows an error, but does not describe the error.  Cannot manipulate Continuous Print and all jobs within Continuous Print are gone. Pause/Resume button also messed up and cannot run any prints manually from regular Octoprint screen.  Print will not load into  STATE window, and several red "?" show up near print time, state, and resend rate but do not show what the issue is (no description of what's wrong).

Screenshots provided below. Printer is a Creality CR-30. 

Restarted Octoprint, tried rebooting system, also uninstalled and reinstalled Continuous Print and restarted Octoprint - to no avail. 

**To Reproduce**
1. Have Continuous Print installed
2. Update Octoprint to newest version (V1.10.0)
3. Go to Continuous Print screen and see error.  Home screen of Octoprint also shows various errors with no ability to diagnose. 

**Expected behavior**
Continuous print works as it did before Octoprint Update.

**Screenshots**
![Octoprint contiunious print error 2024-04-26 after update #2](https://github.com/smartin015/continuousprint/assets/168196202/62d4d4ec-d37d-42a1-8b75-b3886caa9dc1)
![Octoprint contiunious print error 2024-04-26 after update](https://github.com/smartin015/continuousprint/assets/168196202/8041b57d-af63-4186-9862-4ea67fd00230)

**System info:**
[octoprint-systeminfo-20240426135638.zip](https://github.com/smartin015/continuousprint/files/15131003/octoprint-systeminfo-20240426135638.zip)

**Browser logs:**
[10.10.10.97-1714137362264.log](https://github.com/smartin015/continuousprint/files/15131070/10.10.10.97-1714137362264.log)

**Additional context**
Really enjoy Continuous Print, works very well and it's been a huge help in terms of our productivity. Look forward to hearing from you!

**Comment by smartin015** [comment] 2024-04-27 15:46
Hey, thanks for the report - this looks like a duplicate of #249. You can follow along with the fix there.

**Closed by smartin015** 2024-04-27 15:46 UTC
Labels: bug
