### ISSUE TITLE
Octoprint 3.10 not supported

### ISSUE THREAD

**Issue by Rylan-Meilutis** [smartin015/continuousprint#247] opened 2024-04-24 15:22 UTC
**Describe the bug**
The plugin is not functional on octoprint version 3.10.0

**To Reproduce**
1. Install OctoPrint 3.10.0
2. Install the plugin

**Expected behavior**
The plugin to not experience an error when starting up

**Screenshots**
<img width="753" alt="Screenshot 2024-04-24 at 11 16 42 AM" src="https://github.com/smartin015/continuousprint/assets/44624900/cefb193f-269f-4132-a75f-c37b77978a39">

<img width="381" alt="Screenshot 2024-04-24 at 11 23 10 AM" src="https://github.com/smartin015/continuousprint/assets/44624900/e3e3b660-c582-47d3-873a-e55d85b030d4">

**System info:**
[octoprint-systeminfo-20240424151748.zip](https://github.com/smartin015/continuousprint/files/15096565/octoprint-systeminfo-20240424151748.zip)

**Browser logs:**
[octoprint_browser_log-1713972112384.log](https://github.com/smartin015/continuousprint/files/15096606/octoprint_browser_log-1713972112384.log)

**Comment by smartin015** [comment] 2024-04-27 15:46
Hey, thanks for the report - this looks like a duplicate of #249. You can follow along with the fix there.

**Closed by smartin015** 2024-04-27 15:46 UTC
Labels: bug

**Comment by Rylan-Meilutis** [comment] 2024-04-27 22:22
Can confirm that the new fix works, than you so much for speedy work :)
